# Generated by Django 6.0.2 on 2026-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible only to you')], default='public', max_length=10),
        ),
    ]
